
# Category

### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category 1",
  "description": "Description 1"
}

### Get Categories
GET http://localhost:3000/categories

### Get Category By Id
GET http://localhost:3000/categories/249b5021-eb43-4bdb-b195-c3560e50393e